json.extract! project,
              :id,
              :name,
              :driven_issue,
              :standard_analysis,
              :duration,
              :description,
              :limitation,
              :user_id,
              :rule_head,
              :rule_template,
              :tag_list,
              :duration_unit,
              :public,
              :grade,
              :region_id