json.extract! notification,
              :id,
              :subject,
              :content,
              :read,
              :sender_type,
              :sender_id,
              :user_id,
              :additional_info,
              :type
