# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669c3ad1e2f39a69ff6fc1291230f68de5c7d38e296f34749db3e19b7141d8179ef79f187e13ced2de63275a276c6d7fd08bfe3569b95d857ac8a30b516c79d7

test:
  secret_key_base: 7ea620204216ef6cd3df005f31725bffc8bef5baf5aaf6d2f22d834f60f4f6506fb96665cfd1ddd2a8a6d5022e7fa8ac07c556cf0b93c3e03a0b80d67dad7ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
