json.extract! user,
              :id,
              :username,
              :email,
              :first_name,
              :last_name,
              :age,
              :gender,
              :avatar,
              :type,
              :realname,
              :nickname,
              :disciplines,
              :interests