json.extract! @clazz_instance,
              :id,
              :standard,
              :weight,
              :level_1,
              :level_2,
              :level_3,
              :level_4,
              :level_5,
              :level_6,
              :level_7,
              :technique_id